/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package chattingapp.ui;

import chattingapp.models.User;
import chattingapp.utils.AvatarUtil;
import chattingapp.utils.SessionManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CP
 */
public class EditProfileDialog extends javax.swing.JDialog {

    private User currentUser;

    /**
     * Creates new form EditProfileDialog
     */
    public EditProfileDialog() {
        initComponents();
        loadUser();
        btnEdit.requestFocusInWindow();
    }

    private void loadUser() {
        currentUser = SessionManager.getCurrentUser();
        if (currentUser == null) {
            return;
        }

        txtDisplayname.setText(currentUser.getDisplayName());
        txtURLAvatar.setText(currentUser.getAvatarUrl());

        // Fix NPE: Kiểm tra null trước khi set. Mặc định là Male (true) nếu null.
        boolean gender = (currentUser.getGender() != null) ? currentUser.getGender() : true;
        rdMale.setSelected(gender);
        rdFemale.setSelected(!gender);
        String avatarUrlWithCacheBuster = currentUser.getAvatarUrl();
        if (avatarUrlWithCacheBuster != null && avatarUrlWithCacheBuster.startsWith("http")) {
            avatarUrlWithCacheBuster += (avatarUrlWithCacheBuster.contains("?") ? "&" : "?") + "t=" + System.currentTimeMillis();
        }
        previewAvatar(avatarUrlWithCacheBuster);
    }

    private boolean isValidAvatarUrl(String url) {
        if (url == null || url.isEmpty()) {
            return false;
        }

        // 1. Độ dài tối đa
        if (url.length() > 255) {
            return false;
        }

        // 2. Phải bắt đầu bằng http hoặc https
        if (!url.startsWith("http://") && !url.startsWith("https://")) {
            return false;
        }

        // 3. Kiểm tra đuôi file ảnh
        String lower = url.toLowerCase();

        return lower.endsWith(".png")
                || lower.endsWith(".jpg")
                || lower.endsWith(".jpeg")
                || lower.endsWith(".gif")
                || lower.endsWith(".webp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDisplayname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtURLAvatar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("THÔNG TIN CÁ NHÂN");
        getContentPane().add(lblHeader, java.awt.BorderLayout.PAGE_START);

        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel2.add(btnEdit);

        btnSave.setText("Lưu");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        jPanel2.add(btnSave);

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        jPanel2.add(btnCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setMaximumSize(new java.awt.Dimension(80, 80));
        lblAvatar.setMinimumSize(new java.awt.Dimension(80, 80));
        lblAvatar.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel2.setText("Tên hiển thị");

        txtDisplayname.setEditable(false);

        jLabel3.setText("Giới tính");

        txtURLAvatar.setEditable(false);
        txtURLAvatar.addActionListener(this::txtURLAvatarActionPerformed);

        jLabel5.setText("Link ảnh Avatar");

        rdMale.setText("Nam");
        rdMale.setEnabled(false);
        rdMale.addActionListener(this::rdMaleActionPerformed);

        rdFemale.setEnabled(false);
        rdFemale.setLabel("Nữ");
        rdFemale.addActionListener(this::rdFemaleActionPerformed);

        jLabel6.setText("Xác thực mật khẩu");

        txtPassword.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDisplayname, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txtURLAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdMale)
                                .addGap(18, 18, 18)
                                .addComponent(rdFemale))
                            .addComponent(txtPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURLAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplayname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdMale)
                    .addComponent(rdFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel6.getAccessibleContext().setAccessibleName("Xác thực mật khẩu");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void previewAvatar(String url) {
        if (url == null || url.isEmpty()) {
            return;
        }

        new Thread(() -> {
            ImageIcon icon = AvatarUtil.loadAvatar(url, 80, true);

            javax.swing.SwingUtilities.invokeLater(() -> {
                lblAvatar.setIcon(icon);
            });
        }).start();
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        txtURLAvatar.setEditable(true);
        txtDisplayname.setEditable(true);
        rdMale.setEnabled(true);
        rdFemale.setEnabled(true);
        txtPassword.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // 1. Lấy dữ liệu từ UI
        String url = txtURLAvatar.getText().trim();
        String displayName = txtDisplayname.getText().trim();
        boolean gender = rdMale.isSelected();
        char[] passwordChars = txtPassword.getPassword();

        // 2. Client-side Validation
        if (url.isEmpty() || displayName.isEmpty() || passwordChars.length == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tất cả các trường!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!isValidAvatarUrl(url)) {
            JOptionPane.showMessageDialog(this,
                    "Link avatar không hợp lệ!\n"
                    + "- Phải là http/https\n"
                    + "- Đuôi: png, jpg, jpeg, gif, webp\n"
                    + "- Độ dài tối đa 255 ký tự",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 3. Chống spam: Vô hiệu hóa các nút điều khiển
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
        btnEdit.setEnabled(false);

        // 4. Gọi Service cập nhật thông tin
        String password = new String(passwordChars);
        chattingapp.dtos.user.changeprofile.ChangeProfileRequestDTO dto
                = new chattingapp.dtos.user.changeprofile.ChangeProfileRequestDTO(password, displayName, gender, url);

        new chattingapp.services.UserService().changeProfile(dto)
                .thenAccept(v -> {
                    // 5. Cập nhật Session khi thành công
                    User user = SessionManager.getCurrentUser();
                    if (user != null) {
                        user.setAvatarUrl(url);
                        user.setDisplayName(displayName);
                        user.setGender(gender);
                        SessionManager.setSession(SessionManager.getToken(), user);
                    }

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
                        // Xóa password khỏi memory (Security Best Practice)
                        java.util.Arrays.fill(passwordChars, '0');
                        this.dispose(); // CHỈ ĐÓNG KHI THÀNH CÔNG
                    });
                })
                .exceptionally(ex -> {
                    // 6. Xử lý lỗi và khôi phục trạng thái UI
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        // Sử dụng GlobalErrorHandler dùng chung đã xây dựng
                        chattingapp.utils.GlobalErrorHandler.handle(this, ex);

                        // Mở lại nút để người dùng sửa lỗi
                        btnSave.setEnabled(true);
                        btnCancel.setEnabled(true);
                        btnEdit.setEnabled(true);

                        // Clear password để user nhập lại
                        txtPassword.setText("");
                        txtPassword.requestFocus();
                    });
                    return null;
                });

        // TUYỆT ĐỐI KHÔNG gọi this.dispose() ở đây vì code chạy Async
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtURLAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLAvatarActionPerformed
        // TODO add your handling code here:
        //Nhấn enter để xem preview ảnh trước
        previewAvatar(txtURLAvatar.getText());
    }//GEN-LAST:event_txtURLAvatarActionPerformed

    private void rdMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMaleActionPerformed
        rdMale.setSelected(true);
        rdFemale.setSelected(false);
    }//GEN-LAST:event_rdMaleActionPerformed

    private void rdFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemaleActionPerformed
        rdFemale.setSelected(true);
        rdMale.setSelected(false);
    }//GEN-LAST:event_rdFemaleActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextField txtDisplayname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtURLAvatar;
    // End of variables declaration//GEN-END:variables
}
