/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chattingapp.ui;

import chattingapp.dtos.user.forgotpassword.ForgotPasswordOTPRequestDTO;
import chattingapp.dtos.user.login.LoginRequetDTO;
import chattingapp.dtos.user.register.RegisterOTPRequestDTO;
import chattingapp.models.User;
import chattingapp.services.UserService;
import chattingapp.utils.SessionManager;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CP
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/images/logo.png")
        );

        Image img = icon.getImage().getScaledInstance(350, 100, Image.SCALE_SMOOTH);

        lblLogo.setIcon(new ImageIcon(img));
        //Set vị trí ban đầu ở giữa
        this.setLocationRelativeTo(null);
        //Cập nhật text hiển thị khi chưa nhập input cho số điện thoại và mật khẩu
        txtUsername.putClientProperty("JTextField.placeholderText", "Tên đăng nhập");
        txtPassword.putClientProperty("JTextField.placeholderText", "Mật khẩu");

        //Set trước cho Dialog
        txtForgotPasswordUsername.putClientProperty("JTextField.placeholderText", "Nhập tên đăng nhập của bạn...");
        txtOTP.putClientProperty("JTextField.placeholderText", "XX.XX.XX");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        quenMKDialog = new javax.swing.JDialog();
        ForgotPanel = new javax.swing.JPanel();
        UsernamePanel = new javax.swing.JPanel();
        btnGetOTP = new javax.swing.JButton();
        txtForgotPasswordUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NewPasswordPanel = new javax.swing.JPanel();
        jNewPassword = new javax.swing.JPasswordField();
        jNewPasswordConfirm = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        OTPPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtOTP = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PanelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        taoTK = new javax.swing.JLabel();
        quenMK = new javax.swing.JLabel();
        PanelButton = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        quenMKDialog.setMinimumSize(new java.awt.Dimension(400, 500));
        quenMKDialog.setModal(true);

        ForgotPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        ForgotPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        ForgotPanel.setLayout(new java.awt.CardLayout());

        btnGetOTP.setText("Nhận mã xác thực");
        btnGetOTP.addActionListener(this::btnGetOTPActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Nhập tên đăng nhập của bạn");

        javax.swing.GroupLayout UsernamePanelLayout = new javax.swing.GroupLayout(UsernamePanel);
        UsernamePanel.setLayout(UsernamePanelLayout);
        UsernamePanelLayout.setHorizontalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsernamePanelLayout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(txtForgotPasswordUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addGroup(UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsernamePanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnGetOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsernamePanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsernamePanelLayout.setVerticalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtForgotPasswordUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGetOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        ForgotPanel.add(UsernamePanel, "card2");

        jNewPassword.setText("jPasswordField1");

        jNewPasswordConfirm.setText("jPasswordField1");

        jLabel1.setText("Nhập mật khẩu mới");

        jLabel3.setText("Xác nhận mật khẩu mới");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tạo mật khẩu mới");

        btnConfirm.setText("Xác nhận mật khẩu mới");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        javax.swing.GroupLayout NewPasswordPanelLayout = new javax.swing.GroupLayout(NewPasswordPanel);
        NewPasswordPanel.setLayout(NewPasswordPanelLayout);
        NewPasswordPanelLayout.setHorizontalGroup(
            NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPasswordPanelLayout.createSequentialGroup()
                .addGroup(NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewPasswordPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNewPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewPasswordPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel5))
                    .addGroup(NewPasswordPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnConfirm)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        NewPasswordPanelLayout.setVerticalGroup(
            NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPasswordPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addGroup(NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(78, 78, 78)
                .addGroup(NewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(btnConfirm)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        ForgotPanel.add(NewPasswordPanel, "card4");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Vui lòng nhập mã xác thực");

        btnVerify.setText("Xác thực");
        btnVerify.addActionListener(this::btnVerifyActionPerformed);

        javax.swing.GroupLayout OTPPanelLayout = new javax.swing.GroupLayout(OTPPanel);
        OTPPanel.setLayout(OTPPanelLayout);
        OTPPanelLayout.setHorizontalGroup(
            OTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OTPPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(93, 93, 93))
            .addGroup(OTPPanelLayout.createSequentialGroup()
                .addGroup(OTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OTPPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OTPPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        OTPPanelLayout.setVerticalGroup(
            OTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OTPPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        ForgotPanel.add(OTPPanel, "card3");

        quenMKDialog.getContentPane().add(ForgotPanel, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        PanelLogo.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogo.setMaximumSize(new java.awt.Dimension(366, 780));

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.ipady = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 36, 0, 0);
        jPanel1.add(PanelLogo, gridBagConstraints);

        PanelInfo.setBackground(new java.awt.Color(255, 255, 255));

        taoTK.setForeground(new java.awt.Color(0, 104, 255));
        taoTK.setText("Tạo tài khoản");
        taoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taoTKMouseClicked(evt);
            }
        });

        quenMK.setForeground(new java.awt.Color(0, 104, 255));
        quenMK.setText("Quên mật khẩu?");
        quenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quenMKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addComponent(quenMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taoTK))
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taoTK)
                    .addComponent(quenMK))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        jPanel1.add(PanelInfo, gridBagConstraints);

        PanelButton.setBackground(new java.awt.Color(255, 255, 255));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("Đăng nhập");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 40, 0);
        jPanel1.add(PanelButton, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taoTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taoTKMouseClicked
        //Tạo Frame đăng ký
        RegisterFrame registerPage = new RegisterFrame();
        //Mở Frame mới và đóng Frame hiện tại
        registerPage.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_taoTKMouseClicked

    private void btnGetOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetOTPActionPerformed
        String username = txtForgotPasswordUsername.getText().trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(quenMKDialog, "Vui lòng nhập tên đăng nhập!");
            return;
        }

        btnGetOTP.setEnabled(false);
        btnGetOTP.setText("Đang gửi...");

        new UserService().forgotPasswordOTP(new ForgotPasswordOTPRequestDTO(username))
                .thenAccept(v -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(quenMKDialog, "Mã xác thực đã được gửi đến Email của bạn.");
                        // Chuyển sang Card nhập mật khẩu mới
                        java.awt.CardLayout card = (java.awt.CardLayout) ForgotPanel.getLayout();
                        card.show(ForgotPanel, "card4");
                    });
                })
                .exceptionally(ex -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        Throwable cause = (ex instanceof java.util.concurrent.CompletionException) ? ex.getCause() : ex;
                        JOptionPane.showMessageDialog(quenMKDialog, "Lỗi: " + cause.getMessage(), "Thất bại", JOptionPane.ERROR_MESSAGE);
                        btnGetOTP.setEnabled(true);
                        btnGetOTP.setText("Nhận mã xác thực");
                    });
                    return null;
                });
    }//GEN-LAST:event_btnGetOTPActionPerformed

    private void quenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quenMKMouseClicked
        // TODO add your handling code here:
        //Mở Dialog ngay tại vị trí của LoginFrame
        quenMKDialog.setLocationRelativeTo(this);
        quenMKDialog.setVisible(true);
    }//GEN-LAST:event_quenMKMouseClicked

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        String OTP = txtOTP.getText();
        //Kiểm tra OTP ở đây

    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        char[] passwordChars = txtPassword.getPassword();
        String password = new String(passwordChars);

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnLogin.setEnabled(false);
        UserService userService = new UserService();

        userService.login(new LoginRequetDTO(username, password))
                .thenAccept(response -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        User user = new User();
                        user.setUserId(response.userId());
                        user.setUsername(response.username());
                        user.setDisplayName(response.displayName());

                        // FIX: Lấy dữ liệu thực từ response thay vì gán cứng
                        user.setAvatarUrl(response.avatarUrl());
                        user.setGender(response.gender());
                        user.setEmail(response.email()); // Nếu có email để dùng cho UpdateEmailDialog

                        SessionManager.setSession(response.accessToken(), user);
                        new MainFrame().setVisible(true);
                        this.dispose();
                    });
                })
                .exceptionally(ex -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        // 1. Gỡ lớp vỏ CompletionException để lấy nguyên nhân gốc
                        Throwable cause = (ex instanceof java.util.concurrent.CompletionException) ? ex.getCause() : ex;

                        // 2. Kiểm tra nếu là AppException (Lỗi nghiệp vụ từ Backend)
                        if (cause instanceof chattingapp.exceptions.AppException appEx) {
                            String errorCode = appEx.getErrorCode();

                            // 3. So sánh dựa trên Error Code (Chính xác tuyệt đối)
                            if ("ACCOUNT_IS_NOT_ACTIVATED".equals(errorCode)) {
                                int choice = JOptionPane.showConfirmDialog(this,
                                        "Tài khoản chưa kích hoạt. Bạn có muốn nhận mã OTP để xác thực ngay không?",
                                        "Xác thực tài khoản", JOptionPane.YES_NO_OPTION);

                                if (choice == JOptionPane.YES_OPTION) {
                                    userService.getRegisterOTP(new RegisterOTPRequestDTO(username))
                                            .thenAccept(v -> {
                                                javax.swing.SwingUtilities.invokeLater(() -> {
                                                    new OTPFrame(username, username, "REGISTER").setVisible(true);
                                                    this.dispose();
                                                });
                                            })
                                            .exceptionally(otpEx -> {
                                                javax.swing.SwingUtilities.invokeLater(()
                                                        -> JOptionPane.showMessageDialog(this, "Lỗi gửi OTP: " + otpEx.getMessage()));
                                                return null;
                                            });
                                }
                            } else {
                                // Các lỗi nghiệp vụ khác (Sai pass, User không tồn tại, v.v.)
                                JOptionPane.showMessageDialog(this, appEx.getMessage(), "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            // Lỗi hệ thống (Mạng, Server sập, Parse JSON lỗi)
                            JOptionPane.showMessageDialog(this, "Lỗi kết nối: " + cause.getMessage(), "Lỗi hệ thống", JOptionPane.ERROR_MESSAGE);
                        }
                        btnLogin.setEnabled(true);
                    });
                    return null;
                });
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        char[] passwordChars = jNewPassword.getPassword();
        String newPassword = new String(passwordChars);

        char[] confirmChars = jNewPasswordConfirm.getPassword();
        String confirmPassword = new String(confirmChars);
        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ mật khẩu!");
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp!");
            return;
        }
        JOptionPane.showMessageDialog(this, "Mật khẩu hợp lệ. Vui lòng nhập OTP để xác thực.");

        CardLayout card = (CardLayout) ForgotPanel.getLayout();
        card.show(ForgotPanel, "card3"); // chuyển sang OTP
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ForgotPanel;
    private javax.swing.JPanel NewPasswordPanel;
    private javax.swing.JPanel OTPPanel;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel UsernamePanel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnGetOTP;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jNewPassword;
    private javax.swing.JPasswordField jNewPasswordConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel quenMK;
    private javax.swing.JDialog quenMKDialog;
    private javax.swing.JLabel taoTK;
    private javax.swing.JTextField txtForgotPasswordUsername;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
