/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chattingapp.ui;

import chattingapp.components.SideBarPanel;
import chattingapp.models.User;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author CP
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    //Fake data
    private User currentUser;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(User user) {
        this.currentUser = user;
        initComponents();
        initFrame();
        SideBarPanel newSideBar = new SideBarPanel(currentUser);
        leftSplitPane.setLeftComponent(newSideBar);
        leftSplitPane.setDividerLocation(70);
        mainSplitPane.setDividerLocation(300);
    }

    private void initFrame() {
        //Set kích cỡ cho nó lên 3/4 màn hình
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int) (screen.width * 0.75);
        int h = (int) (screen.height * 0.75);
        setSize(w, h);

        //Set ở giữa màn hình
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        leftSplitPane = new javax.swing.JSplitPane();
        chatListPanel1 = new chattingapp.components.ChatListPanel();
        sideBarPanel1 = new chattingapp.components.SideBarPanel();
        chatPanel1 = new chattingapp.components.ChatPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        setResizable(false);

        leftSplitPane.setRightComponent(chatListPanel1);
        leftSplitPane.setLeftComponent(sideBarPanel1);

        mainSplitPane.setLeftComponent(leftSplitPane);
        mainSplitPane.setRightComponent(chatPanel1);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Fake user để test FE
            User fakeUser = new User();
            fakeUser.setUserId("U01");
            fakeUser.setUsername("cp123");
            fakeUser.setDisplayName("CP Dev");
            fakeUser.setPhoneNumber("0987654321");
            fakeUser.setAvatarUrl("https://free.vector6.com/wp-content/uploads/2021/03/0000000556-chim-canh-cut-hoc-bai-tai-hinh-png-38-300x256.png");
            new MainFrame(fakeUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chattingapp.components.ChatListPanel chatListPanel1;
    private chattingapp.components.ChatPanel chatPanel1;
    private javax.swing.JSplitPane leftSplitPane;
    private javax.swing.JSplitPane mainSplitPane;
    private chattingapp.components.SideBarPanel sideBarPanel1;
    // End of variables declaration//GEN-END:variables
}
