/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chattingapp.ui;

import chattingapp.components.ChatPanel;
import chattingapp.components.NotificationListPanel;
import chattingapp.services.StompClientService;
import chattingapp.utils.NotificationManager;
import chattingapp.utils.SessionManager;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author CP
 */
public class MainFrame extends javax.swing.JFrame {

    private static MainFrame instance;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        instance = this;
        initComponents();
        initFrame();
        initData();
        javax.swing.SwingUtilities.invokeLater(() -> {
            getChatPanel().initWebSocket();
        });

    }

    //Hàm dùng để cập nhật lại danh sách tin nhắn
    public static void updateChatList() {
        if (instance != null) {
            instance.chatListPanel1.receiveNewMessage();
        }
    }

    public ChatPanel getChatPanel() {
        return chatPanel1;
    }

    public chattingapp.components.ChatListPanel getChatListPanel() {
        return chatListPanel1;
    }

    private void initData() {
        //Chia giao diện hệ thống, thanh bên trái cho sidebar
        leftSplitPane.setDividerLocation(70);
        //Chia giao diện làm đôi tiếp, bên phải là khung chat, bên trái là danh sách bạn bè và sidebar
        mainSplitPane.setDividerLocation(300);

        //Cấp cao thiết lập kênh đàm thoại, yêu cầu chatPanel tiếng hành load lại giao diện khung chat
        chatListPanel1.setChatSelectionListener(data -> {
            chatPanel1.loadChat(data);
        });
    }

    private void initFrame() {
        //Set kích cỡ cho nó lên 3/4 màn hình
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int) (screen.width * 0.75);
        int h = (int) (screen.height * 0.75);
        setSize(w, h);

        //Set ở giữa màn hình
        setLocationRelativeTo(null);
    }

    public static MainFrame getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        leftSplitPane = new javax.swing.JSplitPane();
        chatListPanel1 = new chattingapp.components.ChatListPanel();
        sideBarPanel1 = new chattingapp.components.SideBarPanel();
        chatPanel1 = new chattingapp.components.ChatPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        setResizable(false);

        leftSplitPane.setRightComponent(chatListPanel1);
        leftSplitPane.setLeftComponent(sideBarPanel1);

        mainSplitPane.setLeftComponent(leftSplitPane);
        mainSplitPane.setRightComponent(chatPanel1);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chattingapp.components.ChatListPanel chatListPanel1;
    private chattingapp.components.ChatPanel chatPanel1;
    private javax.swing.JSplitPane leftSplitPane;
    private javax.swing.JSplitPane mainSplitPane;
    private chattingapp.components.SideBarPanel sideBarPanel1;
    // End of variables declaration//GEN-END:variables
}
