/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chattingapp.ui;

import chattingapp.dtos.user.changeemail.ChangeEmailRequestDTO;
import chattingapp.dtos.user.register.RegisterOTPRequestDTO;
import chattingapp.dtos.user.register.RegisterVerifyRequestDTO;
import chattingapp.models.User;
import chattingapp.services.UserService;
import chattingapp.utils.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author CP
 */
public class OTPFrame extends javax.swing.JFrame {
    private String emailOrUsername;
    private String username;
    private String type; // Biến quyết định luồng API
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OTPFrame.class.getName());

    /**
     * Creates new form OTPVerify
     */
    public OTPFrame(String emailOrUsername, String username, String type) {
        this.emailOrUsername = emailOrUsername;
        this.username = username;
        this.type = type;

        initComponents();
        lblNoti.setText("<html><center>"
                + "Vui lòng nhập mã xác thực<br>"
                + "Chúng tôi đã gửi mã đến <b>" + emailOrUsername + "</b>"
                + "</center></html>");

        txtOTP.putClientProperty("JTextField.placeholderText", "XX.XX.XX");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNoti = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        txtOTP = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        jPanel2 = new javax.swing.JPanel();
        btnReSend = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 40, 40, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblNoti.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblNoti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoti.setText("Text thử để có giao diện");
        lblNoti.setAlignmentX(0.5F);
        jPanel1.add(lblNoti);
        lblNoti.getAccessibleContext().setAccessibleName("");

        jPanel1.add(filler1);

        txtOTP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOTP.setMaximumSize(new java.awt.Dimension(200, 45));
        txtOTP.setMinimumSize(new java.awt.Dimension(200, 45));
        txtOTP.setPreferredSize(new java.awt.Dimension(200, 45));
        jPanel1.add(txtOTP);
        jPanel1.add(filler2);

        btnReSend.setText("Gửi lại mã");
        btnReSend.addActionListener(this::btnReSendActionPerformed);
        jPanel2.add(btnReSend);

        btnVerify.setText("Xác thực");
        btnVerify.setAlignmentX(0.5F);
        btnVerify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerify.addActionListener(this::btnVerifyActionPerformed);
        jPanel2.add(btnVerify);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
String otp = txtOTP.getText().trim();
        if (otp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập OTP");
            return;
        }

        btnVerify.setEnabled(false);
        UserService userService = new UserService();

        if (type.equals("REGISTER")) {
            userService.verifyRegister(new RegisterVerifyRequestDTO(username, otp))
                    .thenAccept(response -> {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(this, "Xác thực thành công!");
                            new LoginFrame().setVisible(true);
                            this.dispose();
                        });
                    })
                    .exceptionally(ex -> handleOTPError(ex));

        } else if (type.equals("CHANGE_EMAIL")) {
            String token = SessionManager.getToken();
            userService.verifyChangeEmail(new ChangeEmailRequestDTO(emailOrUsername, otp))
                    .thenAccept(v -> {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(this, "Đổi Email thành công!");
                            User current = SessionManager.getCurrentUser();
                            current.setEmail(emailOrUsername);
                            this.dispose();
                        });
                    })
                    .exceptionally(ex -> handleOTPError(ex));
        }
    }//GEN-LAST:event_btnVerifyActionPerformed
    private Void handleOTPError(Throwable ex) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            String msg = (ex.getCause() != null) ? ex.getCause().getMessage() : ex.getMessage();
            JOptionPane.showMessageDialog(this, "Lỗi: " + msg, "Xác thực thất bại", JOptionPane.ERROR_MESSAGE);
            btnVerify.setEnabled(true);
        });
        return null;
    }
    private void btnReSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReSendActionPerformed
        btnReSend.setEnabled(false);

        if (type.equals("REGISTER")) {
            new UserService().getRegisterOTP(new RegisterOTPRequestDTO(username))
                    .thenAccept(v -> {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(this, "Mã OTP mới đã được gửi!");
                            btnReSend.setEnabled(true);
                        });
                    })
                    .exceptionally(ex -> {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            btnReSend.setEnabled(true);
                        });
                        return null;
                    });
        }
        // Thêm các nhánh logic gửi lại OTP cho CHANGE_EMAIL nếu cần
    }//GEN-LAST:event_btnReSendActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReSend;
    private javax.swing.JButton btnVerify;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNoti;
    private javax.swing.JTextField txtOTP;
    // End of variables declaration//GEN-END:variables
}
