/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chattingapp.ui;

/**
 *
 * @author CP
 */
public class OTPFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OTPFrame.class.getName());

    /**
     * Creates new form OTPVerify
     */
    public OTPFrame(String SDT) {
        initComponents();
        lblNoti.setText("<html><center>"
                + "Vui lòng nhập mã xác thực<br>"
                + "Chúng tôi đã gửi mã đến <b>" + SDT + "</b>"
                + "</center></html>");

        txtOTP.putClientProperty("JTextField.placeholderText", "XX.XX.XX");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNoti = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        txtOTP = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        jPanel2 = new javax.swing.JPanel();
        btnReSend = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 40, 40, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblNoti.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblNoti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoti.setText("Text thử để có giao diện");
        lblNoti.setAlignmentX(0.5F);
        jPanel1.add(lblNoti);
        lblNoti.getAccessibleContext().setAccessibleName("");

        jPanel1.add(filler1);

        txtOTP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOTP.setMaximumSize(new java.awt.Dimension(200, 45));
        txtOTP.setMinimumSize(new java.awt.Dimension(200, 45));
        txtOTP.setPreferredSize(new java.awt.Dimension(200, 45));
        jPanel1.add(txtOTP);
        jPanel1.add(filler2);

        btnReSend.setText("Gửi lại mã");
        jPanel2.add(btnReSend);

        btnVerify.setText("Xác thực");
        btnVerify.setAlignmentX(0.5F);
        btnVerify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerify.addActionListener(this::btnVerifyActionPerformed);
        jPanel2.add(btnVerify);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        String OTP = txtOTP.getText();
        //Kiểm tra OTP ở đây
    }//GEN-LAST:event_btnVerifyActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReSend;
    private javax.swing.JButton btnVerify;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNoti;
    private javax.swing.JTextField txtOTP;
    // End of variables declaration//GEN-END:variables
}
