/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package chattingapp.ui;

import chattingapp.models.User;
import chattingapp.services.UserService;
import chattingapp.utils.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author CP
 */
public class UpdateEmailDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateEmailDialog.class.getName());

    /**
     * Creates new form UpdatePhoneDialog
     */
    private User currentUser;

    public UpdateEmailDialog() {
        initComponents();
        loadUser();
    }

    private void loadUser() {
        currentUser = SessionManager.getCurrentUser();

        if (currentUser != null) {
            txtCurrentEmail.setText(currentUser.getPhoneNumber());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSaveEmail = new javax.swing.JButton();
        btnCancelEmail = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCurrentEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cập nhật Email");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        btnSaveEmail.setText("Lưu");
        btnSaveEmail.addActionListener(this::btnSaveEmailActionPerformed);

        btnCancelEmail.setText("Hủy");
        btnCancelEmail.addActionListener(this::btnCancelEmailActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnSaveEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnCancelEmail)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEmail)
                    .addComponent(btnCancelEmail))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setText("Email hiện tại");

        txtCurrentEmail.setEditable(false);
        txtCurrentEmail.setToolTipText("");

        jLabel3.setText("Email mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCurrentEmail)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurrentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEmailActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelEmailActionPerformed

    private void btnSaveEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEmailActionPerformed
        String newPhone = txtNewEmail.getText().trim();

        // 1. Validate trống
        if (newPhone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại mới");
            return;
        }

        // 2. Validate định dạng số điện thoại
        if (!newPhone.matches("\\d{10}") && !newPhone.matches("\\d{11}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ (phải có 10 hoặc 11 chữ số)", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Vô hiệu hóa nút để tránh spam
        btnSaveEmail.setEnabled(false);

        // 4. Gọi Service gửi OTP (Backend của bạn dùng username để tìm user và gửi OTP)
        UserService userService = new UserService();
        userService.getRegisterOTP(new chattingapp.dtos.RegisterOTPRequestDTO(currentUser.getUsername()))
                .thenAccept(v -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Mã xác thực đã được gửi đến số điện thoại mới!");

                        // TRUYỀN ĐỦ 2 THAM SỐ:
                        // Thao số 1: newPhone (để hiện lên lblNoti của OTPFrame)
                        // Tham số 2: username (để OTPFrame có cái mà gọi verifyRegister)
                        OTPFrame otp = new OTPFrame(newPhone, currentUser.getUsername());

                        otp.setVisible(true);
                        this.dispose();
                    });
                })
                .exceptionally(ex -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        String msg = (ex.getCause() != null) ? ex.getCause().getMessage() : ex.getMessage();
                        JOptionPane.showMessageDialog(this, "Lỗi gửi OTP: " + msg, "Lỗi", JOptionPane.ERROR_MESSAGE);
                        btnSaveEmail.setEnabled(true);
                    });
                    return null;
                });
    }//GEN-LAST:event_btnSaveEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEmail;
    private javax.swing.JButton btnSaveEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCurrentEmail;
    private javax.swing.JTextField txtNewEmail;
    // End of variables declaration//GEN-END:variables
}
