/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package chattingapp.ui;

import chattingapp.models.User;
import chattingapp.utils.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author CP
 */
public class UpdateEmailDialog extends javax.swing.JDialog {

    /**
     * Creates new form UpdatePhoneDialog
     */
    private User currentUser;

    public UpdateEmailDialog() {
        initComponents();
        loadUser();
    }

    private void loadUser() {
// Đảm bảo lấy đúng User từ Session
        currentUser = SessionManager.getCurrentUser();

        if (currentUser != null) {
            System.out.println("DEBUG: Email hiện tại là: " + currentUser.getEmail()); // Check trong console

            // Cập nhật text cho TextField
            txtCurrentEmail.setText(currentUser.getEmail());

            // Đảm bảo UI cập nhật lại
            txtCurrentEmail.revalidate();
            txtCurrentEmail.repaint();
        } else {
            System.out.println("DEBUG: currentUser bị NULL");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSaveEmail = new javax.swing.JButton();
        btnCancelEmail = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCurrentEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cập nhật Email");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        btnSaveEmail.setText("Lưu");
        btnSaveEmail.addActionListener(this::btnSaveEmailActionPerformed);

        btnCancelEmail.setText("Hủy");
        btnCancelEmail.addActionListener(this::btnCancelEmailActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnSaveEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnCancelEmail)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEmail)
                    .addComponent(btnCancelEmail))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setText("Email hiện tại");

        txtCurrentEmail.setEditable(false);
        txtCurrentEmail.setToolTipText("");

        jLabel3.setText("Email mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCurrentEmail)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurrentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEmailActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelEmailActionPerformed

    private void btnSaveEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEmailActionPerformed
        String newEmail = txtNewEmail.getText().trim();

        // 1. Validate dữ liệu đầu vào (Client-side)
        if (newEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email mới");
            return; // Nút vẫn đang Enabled, user có thể nhập lại
        }

        if (!newEmail.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, "Định dạng email không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (newEmail.equals(currentUser.getEmail())) {
            JOptionPane.showMessageDialog(this, "Email mới không được trùng email hiện tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Xác thực mật khẩu trước khi gọi API
        javax.swing.JPasswordField pwd = new javax.swing.JPasswordField(10);
        int action = JOptionPane.showConfirmDialog(this, pwd, "Nhập mật khẩu hiện tại để xác nhận", JOptionPane.OK_CANCEL_OPTION);

        if (action != JOptionPane.OK_OPTION) {
            return; // User hủy, nút vẫn Enabled
        }

        String password = new String(pwd.getPassword());
        if (password.isBlank()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống");
            return;
        }

        // 3. Chống spam: Disable nút và bắt đầu gọi Service
        btnSaveEmail.setEnabled(false);
        btnSaveEmail.setText("Đang gửi...");

        chattingapp.dtos.user.changeemail.ChangeEmailOTPRequestDTO dto
                = new chattingapp.dtos.user.changeemail.ChangeEmailOTPRequestDTO(password, newEmail);

        new chattingapp.services.UserService().getChangeEmailOTP(dto)
                .thenAccept(v -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Mã xác thực đã được gửi đến email mới!");
                        // Mở form OTP
                        chattingapp.ui.OTPFrame otpFrame = new chattingapp.ui.OTPFrame(newEmail, currentUser.getUsername(), "CHANGE_EMAIL");
                        otpFrame.setVisible(true);
                        this.dispose();
                    });
                })
                .exceptionally(ex -> {
                    // 4. QUAN TRỌNG: Xử lý lỗi và ENABLE lại nút bấm để user sửa thông tin
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        btnSaveEmail.setEnabled(true);
                        btnSaveEmail.setText("Lưu");
                        // Sử dụng GlobalErrorHandler đã xây dựng để thông báo lỗi chuyên nghiệp
                        chattingapp.utils.GlobalErrorHandler.handle(this, ex);
                    });
                    return null;
                });
    }//GEN-LAST:event_btnSaveEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEmail;
    private javax.swing.JButton btnSaveEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCurrentEmail;
    private javax.swing.JTextField txtNewEmail;
    // End of variables declaration//GEN-END:variables
}
