/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.dtos.FriendRequestResponseDTO;
import chattingapp.services.FriendService;
import chattingapp.services.UserService;
import chattingapp.ui.MainFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author CP
 */
public class AddFriendPopupPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFriendPopupPanel
     */
    private Runnable onCloseListener;

    public void setOnCloseListener(Runnable listener) {
        this.onCloseListener = listener;
    }

    public AddFriendPopupPanel() {
        initComponents();
        txtSearch.putClientProperty("JTextField.placeholderText", "Nhập email...");
        loadFriendRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddFriendTab = new javax.swing.JPanel();
        SearchPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        txtFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListFindPanel = new javax.swing.JPanel();
        RequestFriendScroll = new javax.swing.JScrollPane();
        ListRequestPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(350, 500));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(320, 420));

        AddFriendTab.setLayout(new java.awt.BorderLayout());

        SearchPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        SearchPanel.setLayout(new java.awt.BorderLayout());
        SearchPanel.add(txtSearch, java.awt.BorderLayout.CENTER);

        txtFind.setText("🔍");
        txtFind.addActionListener(this::txtFindActionPerformed);
        SearchPanel.add(txtFind, java.awt.BorderLayout.LINE_END);

        AddFriendTab.add(SearchPanel, java.awt.BorderLayout.PAGE_START);

        ListFindPanel.setLayout(new javax.swing.BoxLayout(ListFindPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(ListFindPanel);

        AddFriendTab.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Tìm bạn", AddFriendTab);

        ListRequestPanel.setLayout(new javax.swing.BoxLayout(ListRequestPanel, javax.swing.BoxLayout.Y_AXIS));
        RequestFriendScroll.setViewportView(ListRequestPanel);

        jTabbedPane1.addTab("Lời mời kết bạn", RequestFriendScroll);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
private void loadFriendRequests() {
        //Gọi tới dịch vụ của Friendship
        FriendService service = new FriendService();
        //Lấy tất cả lời mời
        service.getFriendRequests()
                .thenAccept(list -> {
//                    System.out.println("Số request: " + list.size());

//                    for (FriendRequestResponseDTO dto : list) {
////                        System.out.println("Friend name: " + dto.getDisplayName());
//                    }
                    SwingUtilities.invokeLater(() -> {

                        ListRequestPanel.removeAll();
                        //Render từng lời mời thành giao diện
                        for (FriendRequestResponseDTO dto : list) {

                            FriendRequestItemPanel item
                                    = new FriendRequestItemPanel(
                                            dto.getFriendshipId(),
                                            dto.getDisplayName()
                                    );

                            ListRequestPanel.add(item);
                        }

                        ListRequestPanel.revalidate();
                        ListRequestPanel.repaint();

                    });

                })
                .exceptionally(ex -> {

                    ex.printStackTrace();
                    return null;
                });
    }

    public void closePopup() {
        // Gọi listener trước khi đóng
        if (onCloseListener != null) {
            onCloseListener.run();
        }

        // Đồng thời refresh chat list mặc định
        MainFrame.updateChatList();

        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }

    private void searchUser() {

        String email = txtSearch.getText().trim();
        //Dùng userservice để tìm người dùng
        UserService userService = new UserService();

        userService.searchUser(email)
                .thenAccept(user -> {

                    if (user == null) {

                        SwingUtilities.invokeLater(() -> {

                            ListFindPanel.removeAll();
                            ListFindPanel.add(new JLabel("Không tìm thấy người dùng"));

                            ListFindPanel.revalidate();
                            ListFindPanel.repaint();
                        });

                        return;
                    }
                    //Tạo thông tin nếu tìm thấy người dùng có cùng email
                    SearchResultItemPanel item
                            = new SearchResultItemPanel(
                                    user.getDisplayName(),
                                    user.getEmail(),
                                    user.getEmail()
                            );

                    javax.swing.SwingUtilities.invokeLater(() -> {

                        ListFindPanel.removeAll();
                        ListFindPanel.add(item);

                        ListFindPanel.revalidate();
                        ListFindPanel.repaint();

                    });

                })
                .exceptionally(ex -> {

                    ex.printStackTrace();

                    javax.swing.SwingUtilities.invokeLater(() -> {

                        ListFindPanel.removeAll();
                        ListFindPanel.add(new javax.swing.JLabel("Không tìm thấy người dùng"));

                        ListFindPanel.revalidate();
                        ListFindPanel.repaint();

                    });

                    return null;

                });
    }
    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
        searchUser();
    }//GEN-LAST:event_txtFindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddFriendTab;
    private javax.swing.JPanel ListFindPanel;
    private javax.swing.JPanel ListRequestPanel;
    private javax.swing.JScrollPane RequestFriendScroll;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton txtFind;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
