/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.ChatData;
import chattingapp.utils.AvatarUtil;
import chattingapp.utils.TimeUtil;

/**
 *
 * @author CP
 */
public class ChatItemPanel extends javax.swing.JPanel {

    private ChatData data;
    private ChatItemClickListener listener;

    public ChatItemPanel(ChatData data) {
        initComponents();
        this.data = data;
        bindData(data);
        initHoverEffect();
    }

    /**
     * Creates new form ChatItem
     */
//    public ChatItemPanel() {
//
//        initComponents();
//
//    }
    //Hàm xử lý khi click vào item
    //Hãy tưởng tượng cái này như là một kênh đàm thoại, ai muốn sử dụng kênh đàm thoại này này thì phải setup hàm onChatItemClick
    public interface ChatItemClickListener {

        //Kiểm tra coi có ai đăng lắng nghe không, nếu có truyền dữ liệu của nó đi
        void onChatItemClick(ChatData data);
    }

    private void bindData(ChatData data) {

        if (data == null || data.getContact() == null) {
            return;
        }

        // Avatar
        String avatarUrl = data.getContact().getAvatarUrl();
        if (avatarUrl != null && !avatarUrl.isEmpty()) {
            lblAvatar.setIcon(AvatarUtil.loadAvatar(avatarUrl, 40, true));
        } else {
            lblAvatar.setIcon(null); // hoặc set avatar default
        }

        // Tên
        String name = data.getContact().getDisplayName();
        lblName.setText(name != null ? name : "Unknown");
    }
    private boolean selected = false;

    private void initHoverEffect() {

        addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if (!selected) {
                    setBackground(new java.awt.Color(245, 245, 245));
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (!selected) {
                    setBackground(java.awt.Color.WHITE);
                }
            }

            //Dùng để ChatItem thông báo đến toàn hệ thống là có người click
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (listener != null) {
                    listener.onChatItemClick(data);
                }
            }
        });
    }

    public void setSelected(boolean value) {
        selected = value;

        if (selected) {
            setBackground(new java.awt.Color(231, 243, 255));
        } else {
            setBackground(java.awt.Color.WHITE);
        }
    }

    public void setChatItemClickListener(ChatItemClickListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 70));
        setPreferredSize(new java.awt.Dimension(300, 70));
        setLayout(new java.awt.BorderLayout());

        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setOpaque(true);
        lblAvatar.setPreferredSize(new java.awt.Dimension(60, 70));
        add(lblAvatar, java.awt.BorderLayout.WEST);

        textPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        textPanel.setLayout(new javax.swing.BoxLayout(textPanel, javax.swing.BoxLayout.Y_AXIS));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Tên");
        textPanel.add(lblName);

        add(textPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables
}
