/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.ChatData;
import chattingapp.utils.AvatarUtil;
import chattingapp.utils.TimeUtil;

/**
 *
 * @author CP
 */
public class ChatItemPanel extends javax.swing.JPanel {

    public ChatItemPanel(ChatData data) {
        initComponents();
        bindData(data);
        initHoverEffect();
        lblUnread.setVisible(false);
    }

    /**
     * Creates new form ChatItem
     */
    public ChatItemPanel() {

        initComponents();
        
    }

    private void bindData(ChatData data) {

        if (data == null) {
            return;
        }

        // Avatar
        lblAvatar.setIcon(AvatarUtil.loadAvatar(data.getContact().getAvatarUrl(), 40));

        // Tên
        lblName.setText(data.getContact().getDisplayName());

        // Tin nhắn cuối
        if (data.getLastMessage() != null) {
            lblLastMessage.setText(data.getLastMessage().getContent());
            lblTime.setText(
                    data.getLastMessage().getSentAt().toLocalTime().toString()
            );
        } else {
            lblLastMessage.setText("");
            lblTime.setText("");
        }

        // Thời gian
        lblTime.setText(TimeUtil.formatTime(data.getLastMessage().getSentAt()));

        // Số tin chưa đọc
        if (data.getUnreadCount() > 0) {
            lblUnread.setText(String.valueOf(data.getUnreadCount()));
            lblUnread.setVisible(true);
        } else {
            lblUnread.setText("");
            lblUnread.setVisible(false);
        }
    }
    private boolean selected = false;

    private void initHoverEffect() {

        addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if (!selected) {
                    setBackground(new java.awt.Color(245, 245, 245));
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (!selected) {
                    setBackground(java.awt.Color.WHITE);
                }
            }

            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                setSelected(true);
            }
        });
    }

    public void setSelected(boolean value) {
        selected = value;

        if (selected) {
            setBackground(new java.awt.Color(231, 243, 255));
        } else {
            setBackground(java.awt.Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblUnread = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblLastMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 70));
        setPreferredSize(new java.awt.Dimension(300, 70));
        setLayout(new java.awt.BorderLayout());

        lblAvatar.setText("a");
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setPreferredSize(new java.awt.Dimension(60, 70));
        add(lblAvatar, java.awt.BorderLayout.WEST);

        rightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 10));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTime.setForeground(new java.awt.Color(120, 120, 120));
        lblTime.setText("Time");
        rightPanel.add(lblTime);

        lblUnread.setBackground(new java.awt.Color(255, 59, 48));
        lblUnread.setForeground(new java.awt.Color(255, 255, 255));
        lblUnread.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnread.setText("Nhãn");
        lblUnread.setMaximumSize(new java.awt.Dimension(22, 18));
        lblUnread.setOpaque(true);
        lblUnread.setPreferredSize(new java.awt.Dimension(22, 18));
        rightPanel.add(lblUnread);

        add(rightPanel, java.awt.BorderLayout.EAST);

        textPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        textPanel.setLayout(new javax.swing.BoxLayout(textPanel, javax.swing.BoxLayout.Y_AXIS));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Tên");
        textPanel.add(lblName);

        lblLastMessage.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLastMessage.setForeground(new java.awt.Color(100, 100, 100));
        lblLastMessage.setText("Tin nhắn cuối");
        textPanel.add(lblLastMessage);

        add(textPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblLastMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUnread;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables
}
