/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.ChatData;
import chattingapp.models.Message;
import chattingapp.models.User;

/**
 *
 * @author CP
 */
public class ChatListPanel extends javax.swing.JPanel {

    private ChatItemPanel selectedItem;
    private ChatSelectionListener chatSelectionListener;

    /**
     * Creates new form ChatListPanel
     */
    public ChatListPanel() {
        initComponents();
        setupUI();
        fakeData();
    }
    //Hàm này sau này dùng để cập nhật lại list khi có tin nhắn mới
    public void receiveNewMessage(){};
    
    private void setupUI() {

        // Search box đẹp hơn
        txtSearch.putClientProperty("JTextField.placeholderText", "Search...");

        txtSearch.setBorder(
                javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
        );

        // Scroll đẹp hơn
        scrollPane.setBorder(null);
        scrollPane.getVerticalScrollBar().setUnitIncrement(10);

        // Container spacing
        listContainer.setBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0)
        );

        scrollPane.getVerticalScrollBar().putClientProperty("JScrollBar.showButtons", false);
    }
    //Đây là kênh đàm thoại cấp cao, dùng để cho các quản lý giao tiếp tới nhau
    public interface ChatSelectionListener {

        void onChatSelected(ChatData data);
    }
    //Sau này cần một hàm LoadData trả về các đối tượng ChatData (cần tên, avatar, tin nhắn cuối cùng, số tin nhắn chưa đọc)
    private void fakeData() {

        listContainer.removeAll();

        for (int i = 1; i <= 15; i++) {

            // Tạo user giả
            User user = new User();
            user.setDisplayName("Friend " + i);
            user.setAvatarUrl("https://i.pravatar.cc/150?img=" + i);

            // Tạo message giả
            Message msg = new Message();
            msg.setContent("Hello bro this is message " + i);
            msg.setSentAt(
                    java.time.LocalDateTime.now().minusMinutes(i * 5)
            );

            // Tạo ChatData
            ChatData data = new ChatData(user, msg, i % 4);

            // Tạo ChatItemPanel
            ChatItemPanel item = new ChatItemPanel(data);

            // GẮN LISTENER
            //Ông này muốn xài đàm thoại trên kênh nên là định nghĩa một hàm setChatItemClick, hàm sẽ chạy khi có người click vào một item
            item.setChatItemClickListener(clickedData -> {
                //Unselect vật phẩm cũ
                if (selectedItem != null) {
                    selectedItem.setSelected(false);
                }
                //Select vật phẩm mới
                item.setSelected(true);
                selectedItem = item;

                if (chatSelectionListener != null) {
                    chatSelectionListener.onChatSelected(clickedData);
                }
            });

            // Thêm vào list
            listContainer.add(item);
        }

        listContainer.revalidate();
        listContainer.repaint();
    }

    public void setChatSelectionListener(ChatSelectionListener listener) {
        this.chatSelectionListener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        listContainer = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(280, 0));
        setPreferredSize(new java.awt.Dimension(300, 0));
        setLayout(new java.awt.BorderLayout());

        txtSearch.setText("Search");
        txtSearch.setMinimumSize(new java.awt.Dimension(64, 40));
        txtSearch.setPreferredSize(new java.awt.Dimension(71, 45));
        add(txtSearch, java.awt.BorderLayout.PAGE_START);

        listContainer.setLayout(new javax.swing.BoxLayout(listContainer, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(listContainer);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel listContainer;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
