/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.Message;
import chattingapp.models.MessageType;

/**
 *
 * @author CP
 */
public class FileDrawerPanel extends javax.swing.JPanel {

    /**
     * Creates new form FileDrawerPanel
     */
    public FileDrawerPanel() {
        initComponents();
    }

    public interface FileClickListener {

        void onFileClick(String messageId);
    }

    private FileClickListener listener;

    public void setFileClickListener(FileClickListener listener) {
        this.listener = listener;
    }

    public void loadFiles(java.util.List<Message> messages) {

        fileContainer.removeAll();

        for (Message msg : messages) {

            if (msg.getMessageType() == MessageType.TEXT) {
                continue;
            }

            String fileName;

            if (msg.getContent() != null && !msg.getContent().isEmpty()) {
                fileName = msg.getContent();
            } else {
                fileName = extractFileName(msg.getFileUrl());
            }

            String time = msg.getSentAt().toString();

            FileItemPanel item = new FileItemPanel(fileName, time, msg.getMessageId());

            // 🔥 click → báo về ChatPanel
            item.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (listener != null) {
                        listener.onFileClick(msg.getMessageId());
                    }
                }
            });

            fileContainer.add(item);
        }

        fileContainer.revalidate();
        fileContainer.repaint();
    }

    private String extractFileName(String url) {

        if (url == null) {
            return "file";
        }

        int index = url.lastIndexOf("/");

        if (index == -1) {
            return url;
        }

        return url.substring(index + 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDeleteFriend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JScrollPane = new javax.swing.JScrollPane();
        fileContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(230, 230, 230)));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(260, 0));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shared Files");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 10));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        btnDeleteFriend.setText("Xóa bạn");
        btnDeleteFriend.setFocusPainted(false);
        btnDeleteFriend.addActionListener(this::btnDeleteFriendActionPerformed);
        jPanel2.add(btnDeleteFriend);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        JScrollPane.setBorder(null);

        fileContainer.setMaximumSize(new java.awt.Dimension(50, 0));
        fileContainer.setLayout(new javax.swing.BoxLayout(fileContainer, javax.swing.BoxLayout.Y_AXIS));
        JScrollPane.setViewportView(fileContainer);

        jPanel1.add(JScrollPane);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
public interface DeleteFriendListener {

        void onDeleteFriend();
    }

    private DeleteFriendListener deleteListener;

    public void setDeleteFriendListener(DeleteFriendListener listener) {
        this.deleteListener = listener;
    }
    private void btnDeleteFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFriendActionPerformed
        // TODO add your handling code here:
        int result = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa bạn này không?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (result == javax.swing.JOptionPane.YES_OPTION) {
            if (deleteListener != null) {
                deleteListener.onDeleteFriend();
            }
        }

    }//GEN-LAST:event_btnDeleteFriendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnDeleteFriend;
    private javax.swing.JPanel fileContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
