/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

/**
 *
 * @author CP
 */
public class FileItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form FileItemPanel
     */
    public FileItemPanel() {
        initComponents();
    }

    public FileItemPanel(String fileName, String time) {
        initComponents();

        lblFileName.setText(fileName);
        lblTime.setText(time);
    }
    private String messageId;

    public FileItemPanel(String fileName, String time, String messageId) {
        initComponents();
        this.messageId = messageId;

        lblFileName.setText(fileName);
        lblTime.setText(time);
    }

    public String getMessageId() {
        return messageId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFileName = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        setLayout(new java.awt.BorderLayout());

        lblFileName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFileName.setText("report.pdf");
        add(lblFileName, java.awt.BorderLayout.CENTER);

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTime.setForeground(new java.awt.Color(204, 204, 204));
        lblTime.setText("12/3/2026");
        lblTime.setToolTipText("");
        add(lblTime, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
