/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

/**
 *
 * @author CP
 */
public class FriendRequestItemPanel extends javax.swing.JPanel {

    private String requestId;

    /**
     * Creates new form FriendRequestItemPanel
     */
    public FriendRequestItemPanel() {
        initComponents();
    }

    public FriendRequestItemPanel(String requestId, String name) {
        initComponents();

        this.requestId = requestId;
        lblName.setText(name);
    }

    private void acceptRequest() {

        chattingapp.services.FriendService service
                = new chattingapp.services.FriendService();

        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);

        service.acceptFriendRequest(requestId)
                .thenRun(() -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        lblName.setText(lblName.getText() + " (đã kết bạn)");
                    });

                })
                .exceptionally(ex -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        btnAccept.setEnabled(true);
                        btnReject.setEnabled(true);

                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Không thể chấp nhận lời mời"
                        );
                    });

                    return null;
                });
    }

    private void rejectRequest() {

        chattingapp.services.FriendService service
                = new chattingapp.services.FriendService();

        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);

        service.rejectFriendRequest(requestId)
                .thenRun(() -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        lblName.setText("Đã từ chối");
                    });

                })
                .exceptionally(ex -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        btnAccept.setEnabled(true);
                        btnReject.setEnabled(true);

                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Không thể từ chối"
                        );
                    });

                    return null;
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        setLayout(new java.awt.BorderLayout());

        lblAvatar.setText("ava");
        lblAvatar.setMaximumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setMinimumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setPreferredSize(new java.awt.Dimension(40, 40));
        add(lblAvatar, java.awt.BorderLayout.LINE_START);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 0, 0));
        lblName.setText("Tên");
        add(lblName, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnAccept.setBackground(new java.awt.Color(0, 51, 255));
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Đồng ý");
        btnAccept.addActionListener(this::btnAcceptActionPerformed);
        jPanel1.add(btnAccept);

        btnReject.setBackground(new java.awt.Color(204, 204, 204));
        btnReject.setText("Từ chối");
        jPanel1.add(btnReject);

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        acceptRequest();
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
