/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

/**
 *
 * @author CP
 */
public class FriendRequestItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form FriendRequestItemPanel
     */
    public FriendRequestItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        setLayout(new java.awt.BorderLayout());

        lblAvatar.setText("ava");
        lblAvatar.setMaximumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setMinimumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setPreferredSize(new java.awt.Dimension(40, 40));
        add(lblAvatar, java.awt.BorderLayout.LINE_START);

        lblName.setText("Tên");
        add(lblName, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnAccept.setBackground(new java.awt.Color(0, 51, 255));
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Đồng ý");
        jPanel1.add(btnAccept);

        btnReject.setBackground(new java.awt.Color(204, 204, 204));
        btnReject.setText("Từ chối");
        jPanel1.add(btnReject);

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
