/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author CP
 */
public class MessageBubble extends javax.swing.JPanel {

    public MessageBubble(String text, boolean isMine) {

        setLayout(new FlowLayout(
            isMine ? FlowLayout.RIGHT : FlowLayout.LEFT
        ));
        setOpaque(false);

        JLabel lbl = new JLabel("<html>" + text + "</html>");
        lbl.setOpaque(true);
        lbl.setBorder(
            BorderFactory.createEmptyBorder(8,12,8,12)
        );

        if(isMine){
            lbl.setBackground(new Color(0,122,255));
            lbl.setForeground(Color.WHITE);
        }else{
            lbl.setBackground(new Color(240,240,240));
            lbl.setForeground(Color.BLACK);
        }

        add(lbl);
    }
    /**
     * Creates new form MessageBubble
     */
    public MessageBubble() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
