/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author CP
 */
public class MessageBubble extends javax.swing.JPanel {

    public MessageBubble(String text, boolean isMine) {
        initComponents();
        bubblePanel.putClientProperty("FlatLaf.style", "arc:20");
        lblMessage.setText("<html><div style='max-width:220px'>" + text + "</div></html>");

        if (isMine) {

            setLayout(new FlowLayout(FlowLayout.RIGHT));

            bubblePanel.setBackground(new Color(0, 122, 255));
            lblMessage.setForeground(Color.WHITE);

        } else {

            setLayout(new FlowLayout(FlowLayout.LEFT));

            bubblePanel.setBackground(new Color(240, 240, 240));
            lblMessage.setForeground(Color.BLACK);
        }
    }

    /**
     * Creates new form MessageBubble
     */
    public MessageBubble() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bubblePanel = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        bubblePanel.setBackground(new java.awt.Color(255, 255, 255));
        bubblePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        bubblePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubblePanel.setLayout(new java.awt.BorderLayout());

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMessage.setText("jLabel1");
        bubblePanel.add(lblMessage, java.awt.BorderLayout.CENTER);

        add(bubblePanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bubblePanel;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
