/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.Notification;
import java.awt.Color;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author CP
 */
public class NotificationItemPanel extends javax.swing.JPanel {

    private Notification notification;

    /**
     * Creates new form NotificationItemPanel
     */
    public NotificationItemPanel(Notification notification) {

        initComponents();
        this.notification = notification;
        loadData();
    }

    private void loadData() {
        lblContent.setText(notification.getContent());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm dd/MM");

        lblTime.setText(notification.getCreatedAt().format(formatter));

        updateStyle();
    }

    public void updateStyle() {

        if (notification.isRead()) {

            setBackground(new Color(240, 240, 240));
            lblDot.setVisible(false);

        } else {

            setBackground(Color.WHITE);
            lblDot.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDot = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblContent = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(250, 55));
        setMinimumSize(new java.awt.Dimension(250, 55));
        setPreferredSize(new java.awt.Dimension(250, 55));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        lblDot.setBackground(new java.awt.Color(255, 0, 51));
        lblDot.setText("●");
        lblDot.setMaximumSize(new java.awt.Dimension(16, 16));
        lblDot.setMinimumSize(new java.awt.Dimension(16, 16));
        lblDot.setPreferredSize(new java.awt.Dimension(16, 16));
        add(lblDot, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblContent.setText("Nội dung thông báo");
        jPanel1.add(lblContent);

        lblTime.setBackground(new java.awt.Color(204, 204, 204));
        lblTime.setText("Time");
        jPanel1.add(lblTime);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        notification.setRead(true);
        updateStyle();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        updateStyle();
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblDot;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
