/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.Notification;
import java.time.LocalDateTime;
import java.util.List;

/**
 *
 * @author CP
 */
public class NotificationListPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationListPanel
     */
    public NotificationListPanel() {
        initComponents();
        loadFakeData();
    }

    public void setData(List<Notification> list) {
        this.removeAll();

        for (Notification n : list) {
            this.add(new javax.swing.JLabel("🔔 " + n.getContent()));
        }

        this.revalidate();
        this.repaint();
    }

    private void loadFakeData() {

        List<Notification> list = List.of(
                new Notification(
                        "1",
                        "U01",
                        "CP gửi lời mời kết bạn",
                        false,
                        false,
                        LocalDateTime.now(),
                        null
                ),
                new Notification(
                        "2",
                        "U01",
                        "Bạn có tin nhắn mới",
                        true,
                        false,
                        LocalDateTime.now(),
                        null
                )
        );

        for (Notification n : list) {

            NotificationItemPanel item
                    = new NotificationItemPanel(n);

            pnlContainer.add(item);
            pnlContainer.add(javax.swing.Box.createVerticalStrut(3));

        }

        pnlContainer.revalidate();
        pnlContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlContainer.setLayout(new javax.swing.BoxLayout(pnlContainer, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlContainer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
