/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.Notification;
import java.util.List;

/**
 *
 * @author CP
 */
public class NotificationListPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationListPanel
     */
    public NotificationListPanel() {
        initComponents();

    }

    public void setData(List<Notification> list) {
        pnlContainer.removeAll(); // Xóa các item cũ trong container

        for (Notification n : list) {
            // Sử dụng class ItemPanel
            NotificationItemPanel item = new NotificationItemPanel(n);

            // Cố định chiều cao tối đa để không bị giãn
            item.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));

            pnlContainer.add(item);
            pnlContainer.add(javax.swing.Box.createVerticalStrut(5)); // Khoảng cách giữa các thông báo
        }

        // Thêm một Glue ở cuối để đẩy các item lên trên cùng
        //Glue là item tạo khoảng cách ảo sẽ tự chiếm toàn bộ diện tích còn trống
        pnlContainer.add(javax.swing.Box.createVerticalGlue());

        pnlContainer.revalidate();
        pnlContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlContainer.setLayout(new javax.swing.BoxLayout(pnlContainer, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlContainer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
