/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

/**
 *
 * @author CP
 */
public class SearchResultItemPanel extends javax.swing.JPanel {

    private String email;

    /**
     * Creates new form SearchResultItemPanel
     */
    public SearchResultItemPanel(String name, String phone, String email) {
        initComponents();

        lblName.setText(name);
        lblPhone.setText(phone);
        this.email = email;
    }

    private void sendFriendRequest() {

        chattingapp.services.FriendService friendService
                = new chattingapp.services.FriendService();

        btnAddFriend.setEnabled(false);

        friendService.sendFriendRequest(email)
                .thenRun(() -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        btnAddFriend.setText("Đã gửi");
                    });

                })
                .exceptionally(ex -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        btnAddFriend.setEnabled(true);
                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Gửi lời mời thất bại"
                        );
                    });

                    return null;
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        btnAddFriend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(250, 55));
        setMinimumSize(new java.awt.Dimension(250, 55));
        setPreferredSize(new java.awt.Dimension(250, 55));
        setLayout(new java.awt.BorderLayout());

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("ava");
        lblAvatar.setMaximumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setMinimumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setPreferredSize(new java.awt.Dimension(40, 40));
        add(lblAvatar, java.awt.BorderLayout.LINE_START);

        btnAddFriend.setText("Kết bạn");
        btnAddFriend.addActionListener(this::btnAddFriendActionPerformed);
        add(btnAddFriend, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Tên");
        jPanel1.add(lblName);

        lblPhone.setForeground(new java.awt.Color(102, 102, 102));
        lblPhone.setText("số điện thoại");
        lblPhone.setToolTipText("");
        jPanel1.add(lblPhone);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        // TODO add your handling code here:
        sendFriendRequest();
    }//GEN-LAST:event_btnAddFriendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    // End of variables declaration//GEN-END:variables
}
