/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chattingapp.components;

import chattingapp.models.User;
import chattingapp.ui.EditProfileDialog;
import chattingapp.ui.LoginFrame;
import chattingapp.ui.UpdatePasswordDialog;
import chattingapp.ui.UpdateEmailDialog;
import chattingapp.utils.AvatarUtil;
import chattingapp.utils.NotificationManager;
import chattingapp.utils.SessionManager;
import javax.swing.ImageIcon;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;

/**
 *
 * @author CP
 */
public class SideBarPanel extends javax.swing.JPanel {

    private static SideBarPanel instance;
    /**
     * Creates new form SideBarPanel
     */
    //Fake data
    private User currentUser;
    private javax.swing.JLabel lblBadge;

    public SideBarPanel() {
        initComponents();
        instance = this;

        lblBadge = new javax.swing.JLabel();
        lblBadge.setForeground(java.awt.Color.WHITE);
        lblBadge.setBackground(java.awt.Color.RED);
        lblBadge.setOpaque(true);
        lblBadge.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 10));
        lblBadge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadge.setVisible(false);

// Sử dụng JLayeredPane hoặc đơn giản là set Text cho Button nếu không muốn cầu kỳ
        // Nếu bạn muốn giữ lblBadge nổi lên trên:
        btnNotify.setLayout(null); // Tắt layout của button để đặt badge tự do
        btnNotify.add(lblBadge);
        lblBadge.setBounds(25, 0, 15, 15); // Đặt vị trí góc trên bên phải của nút (40x40)

        loadUser();
    }

    public static void updateBadgeExternal() {
        if (instance != null) {
            instance.updateBadge(); // Gọi hàm updateBadge có sẵn của bạn
        }
    }

    private void loadUser() {
        currentUser = SessionManager.getCurrentUser();

        if (currentUser != null) {
            setAvatar(currentUser.getAvatarUrl());
        }
    }

    public void updateBadge() {
        int count = NotificationManager.getUnreadCount();

        javax.swing.SwingUtilities.invokeLater(() -> {
            if (count > 0) {
                lblBadge.setText(String.valueOf(count));
                lblBadge.setVisible(true);
            } else {
                lblBadge.setVisible(false);
            }
        });
    }

    public final void setAvatar(String avatarURL) {
//        lblAvatar.setText("");
        System.out.println("RAW avatar = [" + avatarURL + "]");

        new Thread(() -> {
            ImageIcon icon = AvatarUtil.loadAvatar(avatarURL, 40, true);

            SwingUtilities.invokeLater(() -> {
                lblAvatar.setIcon(icon);
            });
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userMenu = new javax.swing.JPopupMenu();
        menuEditProfile = new javax.swing.JMenuItem();
        menuUpdatePhone = new javax.swing.JMenuItem();
        menuUpdatePassword = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        lblAvatar = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        btnAddFriend = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnNotify = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        menuEditProfile.setText("Chỉnh sửa thông tin");
        menuEditProfile.addActionListener(this::menuEditProfileActionPerformed);
        userMenu.add(menuEditProfile);

        menuUpdatePhone.setText("Cập nhật Email");
        menuUpdatePhone.setToolTipText("");
        menuUpdatePhone.addActionListener(this::menuUpdatePhoneActionPerformed);
        userMenu.add(menuUpdatePhone);

        menuUpdatePassword.setText("Đổi mật khẩu");
        menuUpdatePassword.addActionListener(this::menuUpdatePasswordActionPerformed);
        userMenu.add(menuUpdatePassword);

        menuLogout.setText("Đăng xuất");
        menuLogout.addActionListener(this::menuLogoutActionPerformed);
        userMenu.add(menuLogout);

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(70, 0));
        setPreferredSize(new java.awt.Dimension(70, 100));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler1);

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("av");
        lblAvatar.setAlignmentX(0.5F);
        lblAvatar.setComponentPopupMenu(userMenu);
        lblAvatar.setMaximumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setMinimumSize(new java.awt.Dimension(40, 40));
        lblAvatar.setPreferredSize(new java.awt.Dimension(40, 40));
        lblAvatar.setVerifyInputWhenFocusTarget(false);
        lblAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatarMouseClicked(evt);
            }
        });
        add(lblAvatar);
        add(filler2);

        btnAddFriend.setText("+");
        btnAddFriend.setAlignmentX(0.5F);
        btnAddFriend.setBorderPainted(false);
        btnAddFriend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddFriend.setFocusPainted(false);
        btnAddFriend.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAddFriend.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAddFriend.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAddFriend.addActionListener(this::btnAddFriendActionPerformed);
        add(btnAddFriend);
        add(filler3);

        btnNotify.setText("🔔");
        btnNotify.setAlignmentX(0.5F);
        btnNotify.setBorderPainted(false);
        btnNotify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotify.setFocusPainted(false);
        btnNotify.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNotify.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNotify.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNotify.addActionListener(this::btnNotifyActionPerformed);
        add(btnNotify);
        add(filler4);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarMouseClicked
        // TODO add your handling code here:
        //Bật cái này lên nếu muốn option show khi ấn chuột trái vào avatar
//        userMenu.show(this, evt.getX(), evt.getY());
    }//GEN-LAST:event_lblAvatarMouseClicked

    private void menuEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditProfileActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
            return;
        }

        EditProfileDialog dialogEdit = new EditProfileDialog();
        dialogEdit.setLocationRelativeTo(null);
        dialogEdit.setVisible(true);

    }//GEN-LAST:event_menuEditProfileActionPerformed

    private void menuUpdatePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdatePhoneActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
            return;
        }

        UpdateEmailDialog dialogPhone = new UpdateEmailDialog();
        dialogPhone.setLocationRelativeTo(null);
        dialogPhone.setVisible(true);
    }//GEN-LAST:event_menuUpdatePhoneActionPerformed

    private void menuUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdatePasswordActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
            return;
        }

        UpdatePasswordDialog passDialog = new UpdatePasswordDialog();
        passDialog.setLocationRelativeTo(null);
        passDialog.setVisible(true);
    }//GEN-LAST:event_menuUpdatePasswordActionPerformed

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        // TODO add your handling code here:
        //Tạo nhanh một Dialog thay vì tạo hẳn một dialog mới
        javax.swing.JDialog dialog = new javax.swing.JDialog(
                javax.swing.SwingUtilities.getWindowAncestor(this),
                "Thêm bạn",
                javax.swing.JDialog.ModalityType.APPLICATION_MODAL
        );

        AddFriendPopupPanel panel = new AddFriendPopupPanel();
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Gọi reload chat list
                chattingapp.ui.MainFrame.updateChatList();
            }

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Gọi luôn khi user nhấn nút X
                chattingapp.ui.MainFrame.updateChatList();
            }
        });
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddFriendActionPerformed

    private void btnNotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifyActionPerformed
        // TODO add your handling code here:
        NotificationManager.markAllRead();
        updateBadge();

        JPopupMenu popup = new JPopupMenu();

        NotificationListPanel panel = new NotificationListPanel();
        panel.setData(NotificationManager.getAll());

        panel.setPreferredSize(new java.awt.Dimension(300, 400));

        popup.setLayout(new java.awt.BorderLayout());
        popup.add(panel);

        popup.show(btnNotify, btnNotify.getWidth() + 5, 0);
    }//GEN-LAST:event_btnNotifyActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        SessionManager.clearSession();

        new LoginFrame().setVisible(true);

        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_menuLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnNotify;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JMenuItem menuEditProfile;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuUpdatePassword;
    private javax.swing.JMenuItem menuUpdatePhone;
    private javax.swing.JPopupMenu userMenu;
    // End of variables declaration//GEN-END:variables
}
